version: '3.8'

services:
  tailscale-exit:
    image: tailscale/tailscale:latest
    container_name: tailscale-exit-${CLIENT_NAME:-exit}
    hostname: ${CLIENT_NAME:-exit}-node
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - tailscale-data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_HOSTNAME=${CLIENT_NAME:-exit}-node
      - TS_ACCEPT_DNS=true
      - TS_ROUTES=0.0.0.0/0,::/0
      - TS_EXTRA_ARGS=--advertise-exit-node --accept-routes
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    command: sh -c "tailscaled --tun=userspace-networking & sleep 5 && tailscale up --authkey=$${TS_AUTHKEY} --hostname=$${TS_HOSTNAME} --advertise-exit-node --accept-routes && wait"
    networks:
      - tailscale
    healthcheck:
      test: ["CMD", "tailscale", "status"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  tailscale-data:

networks:
  tailscale:
    driver: bridge